### ISSUE TITLE
[Task] Server_User_Controller_Router 구현 및 테스트

### ISSUE THREAD

**Issue by westtrain** [codestates/Podo#20]
### **ISSUE**

- Group: `server`
- Type: `bug`, `feature`
- Detail: Server_User_Controller_Router 구현 및 테스트

### **TODO**

- [x] 회원 정보 조회
- [x] 프로필 이미지 변경
- [x] 포도머니 인출
- [x] 회원 탈퇴
- [x] Router - users.js

### **Labels**

- Estimated time: `E: 2d`
- Group : `server`
- Sprint: `Sprint_Server_Develop`
- Urgency: `Middle`
