### ISSUE TITLE
[Task] Server_Party_Controller_Router 구현 및 테스트

### ISSUE THREAD

**Issue by westtrain** [codestates/Podo#21]
### **ISSUE**

- Group: `server`
- Type: `bug`, `feature`
- Detail: Server_Party_Controller_Router 구현 및 테스트

### **TODO**

- [x] 유저가 가입한 모든 파티 리스트 조회
- [x] 파티 상세 정보 조회
- [x] 전체 파티 조회
- [x] 날짜별 파티 조회
- [x] 파티 만들기
- [x] OTT 로그인 정보 변경
- [x] 파티 인원 변경
- [x] 파티 가입
- [x] 파티 탈퇴
- [x] Router - parties.js

### **Labels**

- Estimated time: `E: 2d`
- Group : `server`
- Sprint: `Sprint_Server_Develop`
- Urgency: `Middle`
