### ISSUE TITLE
[Task] Server_Payment_Controller_Router 구현 및 테스트

### ISSUE THREAD

**Issue by westtrain** [codestates/Podo#23]
### **ISSUE**

- Group: `server`
- Type: `bug`, `feature`
- Detail: Server_Payment_Controller_Router 구현 및 테스트

### **TODO**

- [x] 유저 결제 정보 조회
- [x] 결제/적립/인출 조회
- [x] 카드 등록
- [x] 카드 변경
- [x] 인출 계좌 등록
- [x] 인출 계좌 변경
- [x] 정산일 등록
- [x] 정산일 변경
- [x] Router - payment.js  

### **Estimated time**

> Pick one
> 

### **Labels**

- Estimated time: `E: 2d`
- Group : `server`
- Sprint: `Sprint_Server_Develop`
- Urgency: `Middle`
