### ISSUE TITLE
[Task] Client_ MyPage SCSS 구현

### ISSUE THREAD

**Issue by LauraBoraKim** [codestates/Podo#26]
### **ISSUE**

- Group: `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### **TODO**

- [ ]  나의 파티 관리
- [ ]  파티 상세페이지
- [ ]  로그인 관리
- [ ]  결제 수단 관리
- [ ]  인출 계좌 관리
- [ ]  정산일 관리
- [ ]  결제/적립/인출 내역

### **Estimated time**

> Pick one
> 

### **Labels**

- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
